hugopl/sidekiq.cr

bench/load.cr
spec/api_spec.cr
spec/job_spec.cr
spec/retry_spec.cr
spec/spec_helper.cr
spec/web_spec.cr
spec/worker_spec.cr
src/sidekiq/api.cr
src/sidekiq/client.cr
src/sidekiq/job.cr
src/sidekiq/server/processor.cr
src/sidekiq/server/retry_jobs.cr
src/sidekiq/server/scheduled.cr
src/sidekiq/web_helpers.cr
src/sidekiq/worker.cr

This seems to work amazingly well.  `perform` arguments can now be of any type as long as they declare how to map them onto JSON.  Serializes down to basic arrays and hashes, deserializes to an arbitrary nesting of typed objects.
```ruby
class Point
JSON.mapping({x: Float64, y: Float64})
def initialize(@x, @y)
end
end
class Circle
JSON.mapping({radius: Int32, diameter: Int32})
def initialize(@radius, @diameter)
end
end
class ComplexWorker
include Sidekiq::Worker
def perform(points : Array(Point), circle : Circle)
end
end
describe Sidekiq::Worker do
describe "arguments" do
it "handles arbitrary complexity" do
p1 = Point.new(1.0, 3.0)
p2 = Point.new(4.3, 12.5)
a = [p1, p2]
ComplexWorker.async.perform(a, Circle.new(9, 17))
msg = Sidekiq.redis { |c| c.lpop("queue:default") }
job = …
```

Handle arguments of arbitrary complexity

---

spec/server_spec.cr
src/sidekiq/middleware.cr

`Middleware#remove` doesn't work now, as crystal Array lacks a `#delete_if` method. Replacing it with `#reject!` and adding a spec for it.  (https://crystal-lang.org/api/0.18.7/Array.html)

Fixing middleware removal, adding spec for that

---

spec/sidekiq/server/fetch_spec.cr
src/sidekiq/server/fetch.cr

If you stop sidekiq when something still in progress and it unable to finish in timely manner I get next error:
```
2016-10-08T13:23:29.028Z 60216 TID-1zo2irk  INFO: Sidekiq v0.6.0 in Crystal 0.19.3
2016-10-08T13:23:29.029Z 60216 TID-1zo2irk  INFO: Licensed for use under the terms of the GNU LGPL-3.0 license.
2016-10-08T13:23:29.029Z 60216 TID-1zo2irk  INFO: Upgrade to Sidekiq Enterprise for more features and support: http://sidekiq.org
2016-10-08T13:23:29.029Z 60216 TID-1zo2irk  INFO: Starting processing with 25 workers
2016-10-08T13:23:29.029Z 60216 TID-1zo2irk  INFO: Press Ctrl-C to stop
2016-10-08T13:23:29.043Z 60216 TID-1zo2i68  JID=95520bc5b6ddbcd4a366da75 INFO: Start
^C2016-10-08T13:23:41.760Z 60216 TID-1zo2irk  INFO: Re-enqueuing 1 busy jobs
RedisError: We are in a pipelined block …
```

Fix reenqueing of jobs when server is stopped

---

spec/worker_spec.cr
src/sidekiq/job.cr
src/sidekiq/worker.cr

If `perform` method of worker has no arguments, I get next error:
```
WARN: {"job":"{\"queue\":\"default\",\"jid\":\"4186fd1d4926273cdfaa9116\",\"class\":\"SimpleJob\",\"args\":,\"created_at\":1476205595.1608269,\"enqueued_at\":1476205595.182435,\"retry\":true}"}
WARN: JSON::ParseException: unexpected token: , at 1:79
```
The problem is in agrs serialization: `\"args\":,\"created_at\"`

Fix defaults for worker without args

---

spec/heartbeat_spec.cr

+ Use `json` parsing instead of **regexp** matching
+ Use `crystal` to get `hostname` instead of backticks 😉

use pure crystal in hb spec

---

shard.yml

First of all, thank you for your awesome work and open sourcing sidekiq.cr. I use it for my hobby project [Crystal ANN](https://crystal-ann.com/) which you may find interesting also for the announcements.
I have a conflict using this shard with [amber framework](https://github.com/amberframework/amber), because amber [uses](https://github.com/amberframework/amber/blob/ff64493a8f94e3c06941963d44f4b92926dcbaf5/shard.yml#L32-L34) a newer crystal redis shard. This tiny PR just points to the latest available crystal-redis:
https://github.com/stefanwille/crystal-redis/releases/tag/v1.9.0

Upgrade crystal-redis to the latest version

---

examples/web.cr
shard.yml
spec/retry_spec.cr
spec/web_spec.cr
src/sidekiq/api.cr
src/sidekiq/client.cr
src/sidekiq/job.cr
src/sidekiq/server/heartbeat.cr
src/sidekiq/server/server.cr

Crystal 0.24.1 is out https://github.com/crystal-lang/crystal/releases/tag/v0.24.1
This PR is about to fix compatibility issues.
Upgraded dependencies:
* kemal https://github.com/kemalcr/kemal/releases/tag/v0.22.0
* keaml-csrf https://github.com/kemalcr/kemal-csrf/releases/tag/v0.4.0
Could you please prepare a new release once it is merged?

Support of crystal 0.24.1

---

spec/web_helpers_spec.cr
src/sidekiq/web_helpers.cr

https://github.com/rails/rails/blob/cfb1e4dfd8813d3d5c75a15a750b3c53eebdea65/activesupport/lib/active_support/number_helper/number_to_delimited_converter.rb
https://github.com/crystal-lang/crystal/issues/5573
---
This inconsistency between frontend and backend was driving me mad 😅 
Comments (138-140) modified by crystal's autoformatter, I can revert if needed.

Port number_with_delimiter method from ActiveSupport

---

spec/heartbeat_spec.cr
spec/sidekiq_spec.cr
spec/web_helpers_spec.cr
src/sidekiq/server/heartbeat.cr
src/sidekiq/server/server.cr

Another quicky - I noticed that `busy` state was always `0` in web ui panel.
Please take a closer look at this, I'm that super familiar with internals, but it seems `busy` state should be read from Processor's `@@worker_state` and getter on `Sidekiq::Server` was never actually used ❓ 
I was looking at Ruby's original implementation to confirm what is the right/expected approach here.
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/launcher.rb#L95-L103
https://github.com/mperham/sidekiq/blob/master/lib/sidekiq/processor.rb#L194-L207
update: aaand let's fix introduced regression in specs, sorry about that, random execution order is random 😅

Register busy count based on Processor's worker_state

---

shard.yml

Why
Redis shard have release a few versions already latest version is 1.11.0
What
Updates the shard dependency file to  use latest version

Upgrade Redis Version

---

shard.yml

Crystal-redis 2.0.0 has been released yesterday and it includes auto reconnecting. This should fix #58 (and I briefly checked that it really seems to do):
```
[truncated]
2018-06-21T13:54:47.594Z 10069 TID-1z87g5c  ERROR: /usr/local/Cellar/crystal-lang/0.25.0_1/src/fiber.cr:29:34 in '->'
2018-06-21T13:54:47.594Z 10069 TID-1z87iio  ERROR: /usr/local/Cellar/crystal-lang/0.25.0_1/src/fiber.cr:29:34 in '->'
2018-06-21T13:54:47.594Z 10069 TID-1z87gg0  ERROR: /usr/local/Cellar/crystal-lang/0.25.0_1/src/fiber.cr:29:34 in '->'
2018-06-21T13:54:47.594Z 10069 TID-1z87h1c  ERROR: /usr/local/Cellar/crystal-lang/0.25.0_1/src/fiber.cr:29:34 in '->'
2018-06-21T13:54:47.594Z 10069 TID-1z87h4w  ERROR: /usr/local/Cellar/crystal-lang/0.25.0_1/src/fiber.cr:29:34 in '->'
2018-06-21T13:54:47.594Z 10069 …
```

Use crystal-redis 2.0

---

src/sidekiq/client.cr

Previously, when using
```cr
sidekiq_options do |job|
job.retry = false
end
```
when submitting a bulk job, the retry wouldn't be copied and jobs would be retried anyway.

Copy retry option when pushing bulk jobs

---

shard.yml

I've had some issues with `shards check` reporting `kemal-session` being out of date after adding Sidekiq to my project.
In a clean repository, run: `shards install && shards check`.
A clean install should report that all dependencies are satisfied.
```
⟩ shards check
Dependencies aren't satisfied. Install them with 'shards install'
```
It turns out that `kemal-csrf@0.4.0` requires  `kemal-session@0.9.0` while this project is referring to the commit for `kemal-session@0.10.0`. Upgrading to `kemal-csrf@0.5.0` resolves the problem.

Upgrade kemal-csrf-dependency

---

shard.yml

The requirement `~> 2.0.0` breaks `shards install` when using newer `stefanwille/crystal-redis` versions (e.g. `2.1.1`).  Changing the requirement to `~> 2.0` resolves that.

Loose Redis version requirement

---

spec/worker_spec.cr
src/sidekiq/worker.cr

Attempting to include the `Sidekiq::Worker` module and using it with a worker class inside a top-level `Worker` namespace (e.g. via `Worker::MyWorker.async.perform`) results in the following compile error:
```
in src/worker/my_worker.cr:19: instantiating 'Worker::MyWorker.class#async()'
Worker::MyWorker.async.perform(user_id, item_id)
^~~~~
in lib/sidekiq/src/sidekiq/worker.cr:112: expanding macro
{% begin %}
^
in macro 'macro_4870787408' /Users/nilsding/Projects/some_project/lib/sidekiq/src/sidekiq/worker.cr:112, line 4:
1.
2.
3.
>  4.         job = Worker::MyWorker::PerformProxy.new
5.         job.klass = self.name
6.         Sidekiq::Worker::OPTION_BLOCKS["Worker::MyWorker"]?.try &.call(job)
7.         job
8.
undefined constant Worker::MyWorker::PerformProxy
```
I think this is because …

Fix namespace scope resolution in Sidekiq::Worker

---

src/web/views/_poll_link.ecr

This PR basically changes the polling check in the `_poll_link.ecr` view to the same one as seen in `_poll_js.ecr`.  The actual fix is accessing the query parameter as a string instead of a symbol.

Fix "Live Poll" button

---

shard.yml
spec/api_spec.cr
spec/web_spec.cr
src/sidekiq/api.cr
src/sidekiq/client.cr
src/sidekiq/core_ext.cr
src/sidekiq/job.cr
src/sidekiq/server/heartbeat.cr
src/sidekiq/server/middleware.cr
src/sidekiq/server/processor.cr
src/sidekiq/server/retry_jobs.cr
src/sidekiq/server/scheduled.cr
src/web/views/dashboard.ecr

Support for Cyrstal 0.27.0 - Latest Version
- Renamed `#epoch(sencods)` to `unix(sencods)`
- Renamed `#epoch_ms(milisencods)` to `unix_ms(milisencods)`
- Renamed `#epoch()` to `to_unix()`
- Renamed `#epoch_f()` to `to_unix_f()`
- Hash#fetch now doesn't have an overload with only one argument. 
For more details see the [changelog](https://github.com/crystal-lang/crystal/releases/tag/0.27.0)

Crystal 0.27.0 support

---

src/sidekiq/api.cr
src/sidekiq/job.cr
src/sidekiq/server/heartbeat.cr
src/sidekiq/server/middleware.cr
src/sidekiq/server/retry_jobs.cr
src/sidekiq/server/scheduled.cr

PR #73 provided Crystal 0.27.0 support.  Unfortunately, some occurrences of `epoch_f` were replaced with `to_unix_ms`, which was probably not intended, and made the `Busy` page (and probably other usages of the Sidekiq API in a Crystal app as well) break with an error similar to this:
```
Exception: cast from Int64 to Float+ failed, at /usr/local/Cellar/crystal/0.27.0/src/json/any.cr:189:5:189 (TypeCastError)
from /usr/local/Cellar/crystal/0.27.0/src/json/any.cr:0:5 in 'as_f'
from src/sidekiq/api.cr:640:21 in 'started_at'
from src/sidekiq/web.cr:40:33 in '->'
from lib/kemal/src/kemal/route.cr:255:3 in '->'
from lib/kemal/src/kemal/route_handler.cr:255:3 in 'process_request'
from lib/kemal/src/kemal/route_handler.cr:17:7 in 'call'
from …
```

Use to_unix_f where epoch_f was previously used

---

spec/stats_spec.cr
src/sidekiq/api.cr

Time#date that will now return a Tuple of {year, month, day}. You can keep using Time#at_beginning_of_day if a Time instance is wanted. Read more at [#5822](https://github.com/crystal-lang/crystal/pull/5822).

Update date to be compatible for 0.28.0

---

README.md

http://shards.rocks doesn't exists anymore.

Remove broken banners from README.

---

src/sidekiq/server/cli.cr

No log output is show anymore on tests since tests are using `Log::MemoryBackend`.

Remove hack to disable banner on tests.

---

shard.yml
spec/retry_spec.cr
spec/spec_helper.cr
src/sidekiq/server/retry_jobs.cr

- Correctly set retried_at and failed_at fields.
- Add timecop development dependency to test job retries.
Issue found at https://github.com/mperham/sidekiq.cr/commit/a4b6384220256704d1b045bea057dbdd00ca6f0d#r48541525

Fix regression on retry jobs after a4b6384220256704d1b045bea057dbdd00ca6f0d

---

shard.yml

Out of the box, I encountered the following message after creating a copy of the provided example for `web.cr`
```
$ crystal build --release web.cr
Showing last frame. Use --error-trace for full trace.
In lib/kemal/src/kemal/static_file_handler.cr:55:25
55 | last_modified = modification_time(file_path)
^----------------
```
It probably has to do with [modification_time being a private method?](https://github.com/kemalcr/kemal/blob/ae7cda829162ea27668b3fc79cd1868026e25098/src/kemal/static_file_handler.cr#L79). Anyway, after forking the project and changing Kemal's target version the web UI file compiled without problems.
Might also want to change the instructions, as they instruct to compile it with `crystal compile` but the new command is `crystal build`.

Bumps Kemal 1.0.0 -> 1.3.0

---

.ameba.yml
.github/workflows/build.yml
shard.yml
src/sidekiq/api.cr
src/sidekiq/client.cr

Specify just the minimal version of dependencies that are expected to work, so we don't lock the version of anyone that also depends on these libs in their projects.
In case of some future version of these dependencies don't work with sidekiq, a bug will be filledand we can fix it, so everybody will be always happy.

Update shard dependencies.

---

.github/workflows/build.yml
shard.yml

So people don't need to wait for ameba being compiled when running shards install.

Remove ameba from development dependencies and use it as a Github action instead
